-- MySQL Script generated by MySQL Workbench
-- Wed Nov  2 22:52:42 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema codenlighter
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema codenlighter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `codenlighter` DEFAULT CHARACTER SET utf8 ;
USE `codenlighter` ;

-- -----------------------------------------------------
-- Table `codenlighter`.`auth_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codenlighter`.`auth_group` ;

CREATE TABLE IF NOT EXISTS `codenlighter`.`auth_group` (
  `id` INT NOT NULL,
  `name` VARCHAR(80) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codenlighter`.`auth_group_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codenlighter`.`auth_group_permissions` ;

CREATE TABLE IF NOT EXISTS `codenlighter`.`auth_group_permissions` (
  `id` INT NOT NULL,
  `group_id` INT NULL,
  `permission_id` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_group_permissions_group_id`
    FOREIGN KEY ()
    REFERENCES `codenlighter`.`auth_group` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group_permissions_permission_id`
    FOREIGN KEY ()
    REFERENCES `codenlighter`.`auth_permission` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codenlighter`.`auth_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codenlighter`.`auth_permission` ;

CREATE TABLE IF NOT EXISTS `codenlighter`.`auth_permission` (
  `id` INT NOT NULL,
  `name` VARCHAR(250) NULL,
  `codename` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codenlighter`.`auth_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codenlighter`.`auth_user` ;

CREATE TABLE IF NOT EXISTS `codenlighter`.`auth_user` (
  `id` INT NOT NULL,
  `username` VARCHAR(150) NULL,
  `first_name` VARCHAR(150) NULL,
  `last_name` VARCHAR(150) NULL,
  `password_id` INT NULL,
  `email` VARCHAR(254) NULL,
  `is_active` TINYINT NULL,
  `is_admin` TINYINT NULL,
  `is_super_admin` TINYINT NULL,
  `date_joined` TIME NULL,
  `last_login` TIME NULL,
  `session_id` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_session_id`
    FOREIGN KEY ()
    REFERENCES `codenlighter`.`auth_user_session` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_password_id`
    FOREIGN KEY (`password_id`)
    REFERENCES `codenlighter`.`auth_user_password` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `username_UNIQUE` ON `codenlighter`.`auth_user` (`username` ASC) VISIBLE;

CREATE INDEX `fk_user_password_id_idx` ON `codenlighter`.`auth_user` (`password_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `codenlighter`.`auth_user_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codenlighter`.`auth_user_groups` ;

CREATE TABLE IF NOT EXISTS `codenlighter`.`auth_user_groups` (
  `id` INT NOT NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_auth_user_id_groups`
    FOREIGN KEY ()
    REFERENCES `codenlighter`.`auth_user` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_auth_group_id_user_groups`
    FOREIGN KEY ()
    REFERENCES `codenlighter`.`auth_group` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codenlighter`.`auth_user_password`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codenlighter`.`auth_user_password` ;

CREATE TABLE IF NOT EXISTS `codenlighter`.`auth_user_password` (
  `id` INT NOT NULL,
  `password` VARCHAR(255) NULL,
  `salt` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codenlighter`.`auth_user_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codenlighter`.`auth_user_permissions` ;

CREATE TABLE IF NOT EXISTS `codenlighter`.`auth_user_permissions` (
  `id` INT NOT NULL,
  `user_id` INT NULL,
  `permission_id` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_permission_user_id`
    FOREIGN KEY ()
    REFERENCES `codenlighter`.`auth_user` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_permission_permission_id`
    FOREIGN KEY ()
    REFERENCES `codenlighter`.`auth_permission` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codenlighter`.`auth_user_session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codenlighter`.`auth_user_session` ;

CREATE TABLE IF NOT EXISTS `codenlighter`.`auth_user_session` (
  `key` INT NOT NULL,
  `create_time` TIME NULL,
  `ip_address` VARCHAR(45) NULL,
  PRIMARY KEY (`key`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
